http:
  enabled: true
  host: 0.0.0.0
  port: '${APM_MONITORING_PORT}'

monitoring.enabled: false

apm-server: 
  host: '0.0.0.0:${APM_PORT}'
  rum: 
    enabled: true
    allow_origins: ['*']
    


logging.level: debug

setup.kibana:
  host: '${KIBANA_HOST}'
  username: '${KIBANA_USERNAME}'
  password: '${KIBANA_PASSWORD}'

output.elasticsearch:
  hosts: '${ELASTIC_HOST}'
  username: "elastic"
  password: '${ELASTIC_PASSWORD}'
  ssl.verification_mode: "none"